// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByf5Et4TntBPMx_UV2KIaRESNoFpelELk',
    appId: '1:438824018210:web:1a51493ec21b311b9d057b',
    messagingSenderId: '438824018210',
    projectId: 'wx-styleloft-flutter-project',
    authDomain: 'wx-styleloft-flutter-project.firebaseapp.com',
    storageBucket: 'wx-styleloft-flutter-project.firebasestorage.app',
    measurementId: 'G-PTCF7VW1W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVesl4Yh2wh9fznSdmWjxq1Fwy3D2xN1A',
    appId: '1:438824018210:android:f41baa8a2711b3ab9d057b',
    messagingSenderId: '438824018210',
    projectId: 'wx-styleloft-flutter-project',
    storageBucket: 'wx-styleloft-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvSZIz09JTiJqq_Q6YJiZia93MNyYbNZU',
    appId: '1:438824018210:ios:872e13bf63efbe109d057b',
    messagingSenderId: '438824018210',
    projectId: 'wx-styleloft-flutter-project',
    storageBucket: 'wx-styleloft-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.wxStyleloftProjectFlutter',
  );
}
